# Generated by Django 5.2.7 on 2025-11-17 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeadmin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeadmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
